name: ah

on:
  schedule:
    - cron: "0 3 * * *" # GitHub uses UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DataFolderName: ./data/ah

    steps:
      - uses: actions/checkout@v2

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Hap, UncommonSense.AH, UncommonSense.iCalendar -Scope CurrentUser

      - name: Create data folder
        shell: pwsh
        run: |
          if (-not (Test-Path -Path $env:DataFolderName -PathType Container))
          {
            New-Item -Path $env:DataFolderName -ItemType Directory | Out-Null
          }

      - name: Update calendar file
        shell: pwsh
        run: |
          1844, 1541
          | Get-AhStore
          | ForEach-Object {
            $CurrentStore = $_

            $CurrentStore.OpeningHours
            | ForEach-Object { New-CalendarEvent -Start $_.From -End $_.To -Summary $CurrentStore.Name -Description $CurrentStore.Address }
            | Export-Calendar -Name $CurrentStore.Name -Path (Join-Path -Path $env:DataFolderName -ChildPath "$($CurrentStore.ID).ics")
          }

      - name: Push changes to git repo
        run: |
          git config --global user.name 'Jan Hoek'
          git config --global user.email 'github@uncommonsense.nl'
          git remote set-url origin https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
          git pull
          git add ./data/ah/*
          git commit -am 'Updated AH files'
          git push
