name: watmaakthetlevendemoeitewaard

on:
  schedule:
    - cron: "22 5 * * 5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pup
        shell: bash
        run: |
          go get github.com/ericchiang/pup
          export GOROOT=/usr/bin/go
          cd ~/go/bin
          sudo cp pup /usr/bin
          pup --version

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module UncommonSense.Nrc, UncommonSense.Rss -Scope CurrentUser

      - name: Get Recent data
        shell: pwsh
        run: |
          Get-WatMaaktHetLevenDeMoeiteWaard
          | Select-Object -First 10
          | ForEach-Object {
            New-RssFeedItem `
              -ID $_.Url `
              -Title $_.Title `
              -Description (($_.Body | ForEach-Object { $_.Trim()} | Where-Object {$_} | ForEach-Object { "<p>$($_)</p>"}) -join "`n") `
              -PubDate $_.Date }
          | New-RssFeed `
            -Title 'Wat maakt het leven de moeite waard' `
            -Link 'https://www.nrc.nl/rubriek/wat-maakt-het-leven-de-moeite-waard/' `
            -Description 'Wat maakt het leven de moeite waard'
          | Set-Content -Path ./data/watmaakthetlevendemoeitewaard.xml

      - name: Commit and push feed
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated" || echo "No changes to commit"
          git push
